#!python3

import sys
import os
import pickle
import utils

min_timestamp = 0
#min_timestamp = 3600 * 24 * 1

filename = sys.argv[1]
save_to = '{}.png'.format(os.path.splitext(filename)[0])

managers = pickle.load(open(filename, 'rb'))
if not isinstance(managers, list):
    managers = [managers]
utils.plot_difficulty(managers, min_timestamp=min_timestamp, save_to=save_to)
os.system('open {}'.format(save_to))
